---
kubernetes:
  children:
    master:
      hosts:
        mango:
          ansible_host: 172.16.20.10
        melon:
          ansible_host: 172.16.20.11
        nectarine:
          ansible_host: 172.16.20.12
    worker:
      hosts:
        orange:
          ansible_host: 172.16.20.13
          rook_devices:
            - /dev/disk/by-id/ata-C400-MTFDDAK256MAM_000000001310036EC8C2
        passionfruit:
          ansible_host: 172.16.20.14
          rook_devices:
            - /dev/disk/by-id/ata-Samsung_SSD_850_PRO_256GB_S1SUNSAG339306E
        papaya:
          ansible_host: 172.16.20.15
          rook_devices:
            - /dev/disk/by-id/ata-SAMSUNG_SSD_830_Series_S0XZNEAC507187
