kind: Secret
ansible_user: ENC[AES256_GCM,data:1cfvMw==,iv:vvug0xxGIMaf2hhVL12xvhr488gLvwraeteoTlHVeys=,tag:JnTeGPQEHlScbvE51XaRew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:y5WYew==,iv:612ZFk0s+3XgCiFhuGPWUNFyaXVwYOWeOclyEgVsmb4=,tag:aNamChcCEagpvubmmZdHIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ructuyptv24l6qv7c40lqq75hvvgjejtwgpdj30rgl25ffdw0dcsx6eu7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2dlRnJpNVB0N0Rhanps
            cHdoWk5qM3FnZUYvdjdKTEU0Y21mQ3JodkQwCnlzdGRIWXRKNnEzZ2Y2Tms5WXJz
            NlVnZTJhVjVnc2ppVENwTjlFTUs5YWcKLS0tIEpVSnQ1a3lid01UTUxtVnZLZXp1
            R1pPQ2tnUmpQS05Vb0QwSlFteWVVTGMK7tgPHvlgU7pNsfSHCuKkSrCxGUvqmMbP
            b+LQ8Zs2OPyTe5qf0OTVbAPW/flYt4G0UMb8/LK/AzJfRxlk9pNHUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-22T23:27:52Z"
    mac: ENC[AES256_GCM,data:wPhdW7JmR2hUwVqG4//lqkja+DsX9+YJDxyvctYSYuFsqFX0ndy/ZsBExflKoCqD55aAyyfsSdfRnr9GmuovjY/Eblf0mpS0qHup0T+kul/Pkqw261YUSo/IorxoDhKzx4qHnUrgKdSRivkVvaqGFHuHu4a/Y5LWj/aUbI3USRE=,iv:jraXWgDqjy/rrYMbW5XaJkKPTj6gA0JyJEkCxKPFcfY=,tag:1JKW9BzjFvNhvsu0tG0VEQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
